### ISSUE TITLE
Question RE: “Get bash aliases and functions”

### ISSUE THREAD

**Issue by Zearin** [ttscoff/dotfiles#1]
On [line 354 of your `.bash_profile`](https://github.com/ttscoff/dotfiles/blob/master/.bash_profile#L354), you source `.bashrc` with the comment “Get bash aliases and functions”.

However, your `.bash_profile` is itself **full** of (awesome and inspirational!) aliases and functions.

How do you determine which file to put your aliases and functions in?

**Comment by ttscoff** [comment]
I'm currently using [bash-it](https://github.com/revans/bash-it) as a way of organizing all of my functions and aliases. I haven't updated this repository in a while, but I should. I have a ton of new stuff :).

**Comment by Zearin** [comment]
> I'm currently using bash-it as a way of organizing all of my functions and aliases.

Oh, awesome!  I’ll check it out…

>  I haven't updated this repository in a while, but I should. I have a ton of new stuff :).

You totally should!  I’m looking forward to the next update. :)
